apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: my-auth
spec:
  virtualhost:
    fqdn: foo.com
    tls:
      secretName: kuard
      clientValidation:
        caSecret: client-kuard
    authorization:
      extensionRef:
        name: my-external-auth
  routes:
    - conditions:
      - prefix: /
      services:
      - name: kuard
        port: 8080
